=== afzafri/CSC570-XML-Project/cleaningservice.dtd
<!-- DTD created at Tue Dec 05 12:50:29 SGT 2017 with EditiX. Please insert an encoding attribute header for converting any DTD  -->

<!ELEMENT  cleaningservice (company,houses)>
<!ELEMENT  company (name,address,contact,staff,rate)>

<!ELEMENT  staff (manager, cleaners)>
<!ELEMENT  manager (name, contact)>
<!ELEMENT  cleaners (cleaner*)>
<!ELEMENT  rate (#PCDATA)>
<!ELEMENT  houses (house*)>
<!ELEMENT  house (address,owner,date,schedule)>
<!ELEMENT  address (street,city,state,postcode)>
<!ELEMENT  owner (name,contact)>
<!ELEMENT  contact (phone, email)>
<!ELEMENT  start_hire (#PCDATA)>
<!ELEMENT  end_hire (#PCDATA)>
<!ELEMENT  schedule (month+)>
<!ELEMENT  month (week+)>
<!ELEMENT  week (day+)>
<!ELEMENT  day (date,duration,cleaner)>
<!ELEMENT  date (#PCDATA|start_hire|end_hire)*>
<!ELEMENT  duration (#PCDATA)>
<!ELEMENT  cleaner (#PCDATA|name)*>
<!ELEMENT  name (#PCDATA)>
<!ELEMENT  street (#PCDATA)>
<!ELEMENT  city (#PCDATA)>
<!ELEMENT  state (#PCDATA)>
<!ELEMENT  postcode (#PCDATA)>
<!ELEMENT  phone (#PCDATA)>
<!ELEMENT  email (#PCDATA)>

<!ATTLIST rate  unit CDATA #FIXED "RM">
<!ATTLIST rate  duration CDATA #REQUIRED>
<!ATTLIST house  type (bungalow|penthouse|terrace|apartment|condominium) #REQUIRED>
<!ATTLIST month  name (january|february|march|april|may|june|july|august|september|october|november|december) #REQUIRED>
<!ATTLIST day  name (monday|tuesday|wednesday|thursday|friday|saturday|sunday) #REQUIRED>
<!ATTLIST duration  unit CDATA #FIXED "hour">

<!ENTITY company "Kospek Cleaning Sdn. Bhd.">

=== afzafri/CSC570-XML-Project/cleaningservice.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cleaningservice SYSTEM "cleaningservice.dtd">
<cleaningservice>
  <company>
  
    <name>Kospek Cleaning Sdn. Bhd.</name>
    
    <address>
      <street>No 4, Tapah Road</street> 
      <city>Tapah</city>
      <state>Perak</state> 
      <postcode>34500</postcode>
    </address>
    
    <contact>
      <phone>04-9651234</phone>
      <email>kospekcleaning@gmail.com</email>
    </contact>
    
    <staff>
      <manager>
        <name>Aaron Aziz Bin Mustapha</name>
        <contact>
          <phone>0175897541</phone>
          <email>aaron9@gmail.com</email>
        </contact>
      </manager>
      
      <cleaners>
        <cleaner>
          <name>Muhammad Syam Bin Md Ali</name>
        </cleaner>
        <cleaner>
          <name>Hamidun Bin Abdul Izzat</name>
        </cleaner>
        <cleaner>
          <name>Hamidah Binti Abu Bakar</name>
        </cleaner>
        <cleaner>
          <name>Ghazali Bin Md Isa</name>
        </cleaner>
        <cleaner>
          <name>Mohd Yahya Bin Idris</name>
        </cleaner>
        <cleaner>
          <name>Nurul Fatimah Binti Ahmad Daud</name>
        </cleaner>
        <cleaner>
          <name>Nur Zarina Binti Zakaria</name>
        </cleaner>
        <cleaner>
          <name>Johan Bin Razak</name>
        </cleaner>
        <cleaner>
          <name>Mustapha Aziz Bin Syakirin</name>
        </cleaner>
        <cleaner>
          <name>Othman Bin Kamarul Zaman</name>
        </cleaner>
        <cleaner>
          <name>Jamal Abdillah Bin Zulkifli</name>
        </cleaner>
        <cleaner>
          <name>Yusrita Binti Fadhli</name>
        </cleaner>
        <cleaner>
          <name>Muhammad Aqil Bin Mohd Darmian</name>
        </cleaner>
        <cleaner>
          <name>Usop Bin Santorian</name>
        </cleaner>
        <cleaner>
          <name>Lisa Suhada Bin Abdul Halim</name>
        </cleaner>
      </cleaners>
      
    </staff>
    
    <rate unit="RM" duration="per hour">10</rate>
    
  </company>
  
  <houses>
  
    <house type="bungalow">
      <address>
        <street>Taman Sena</street> 
        <city>Kangar</city>
        <state>Perlis</state> 
        <postcode>02400</postcode>
      </address>
      
      <owner>
        <name>Muhammad Afif Zafri Bin Khuzairi</name>
        <contact>
          <phone>0175897541</phone>
          <email>afzafri@gmail.com</email>
        </contact>
      </owner>
      
      <date>
        <start_hire>2017/01/01</start_hire>
        <end_hire>2017/02/28</end_hire>
      </date>
      
      <schedule>
        <month name="january">
            <week>
              <day name="saturday">
                <date>2017/01/02</date>
                <duration unit="hour">5</duration>
                <cleaner>Usop Bin Santorian</cleaner>
              </day>
              
              <day name="sunday">
                <date>2017/01/03</date>
                <duration unit="hour">3</duration>
                <cleaner>Lisa Suhada Bin Abdul Halim</cleaner>
              </day>
            </week>
            
            <week>
              <day name="tuesday">
                <date>2017/01/05</date>
                <duration unit="hour">2</duration>
                <cleaner>Johan Bin Razak</cleaner>
              </day>
              
              <day name="sunday">
                <date>2017/01/10</date>
                <duration unit="hour">1</duration>
                <cleaner>Lisa Suhada Bin Abdul Halim</cleaner>
              </day>
            </week>
            
            <week>
              <day name="wednesday">
                <date>2017/01/18</date>
                <duration unit="hour">6</duration>
                <cleaner>Nurul Fatimah Binti Ahmad Daud</cleaner>
              </day>
              
              <day name="saturday">
                <date>2017/01/21</date>
                <duration unit="hour">5</duration>
                <cleaner>Muhammad Aqil Bin Mohd Darmian</cleaner>
              </day>
            </week>
            
            <week>
              <day name="monday">
                <date>2017/01/23</date>
                <duration unit="hour">3</duration>
                <cleaner>Usop Bin Santorian</cleaner>
              </day>
              
              <day name="friday">
                <date>2017/01/27</date>
                <duration unit="hour">4</duration>
                <cleaner>Lisa Suhada Bin Abdul Halim</cleaner>
              </day>
            </week>
        </month>
        
        <month name="february">
            <week>
              <day name="thursday">
                <date>2017/02/02</date>
                <duration unit="hour">4</duration>
                <cleaner>Othman Bin Kamarul Zaman</cleaner>
              </day>
              
              <day name="friday">
                <date>2017/02/03</date>
                <duration unit="hour">6</duration>
                <cleaner>Johan Bin Razak</cleaner>
              </day>
            </week>
            
            <week>
              <day name="sunday">
                <date>2017/02/05</date>
                <duration unit="hour">3</duration>
                <cleaner>Othman Bin Kamarul Zaman</cleaner>
              </day>
              
              <day name="tuesday">
                <date>2017/02/07</date>
                <duration unit="hour">3</duration>
                <cleaner>Hamidun Bin Abdul Izzat</cleaner>
              </day>
              
              <day name="friday">
                <date>2017/02/10</date>
                <duration unit="hour">2</duration>
                <cleaner>Nur Zarina Binti Zakaria</cleaner>
              </day>
            </week>
        </month>
      </schedule>
    </house>

    <house type="penthouse">
      <address>
        <street>Taman Ria</street> 
        <city>Sungai Petani</city>
        <state>Kedah</state> 
        <postcode>08000</postcode>
      </address>
      
      <owner>
        <name>Mohd Asyraf Bin Md Surani</name>
        <contact>
          <phone>0124568745</phone>
          <email>acab@gmail.com</email>
        </contact>
      </owner>
      
      <date>
        <start_hire>2017/02/01</start_hire>
        <end_hire>2017/03/28</end_hire>
      </date>
      
      <schedule>
        <month name="february">
            <week>
              <day name="saturday">
                <date>2017/02/04</date>
                <duration unit="hour">5</duration>
                <cleaner>Ghazali Bin Md Isa</cleaner>
              </day>
              
              <day name="monday">
                <date>2017/02/06</date>
                <duration unit="hour">3</duration>
                <cleaner>Yusrita Binti Fadhli</cleaner>
              </day>
              
              <day name="wednesday">
                <date>2017/02/08</date>
                <duration unit="hour">7</duration>
                <cleaner>Hamidah Binti Abu Bakar</cleaner>
              </day>
            </week>
            
            <week>
              <day name="tuesday">
                <date>2017/02/14</date>
                <duration unit="hour">5</duration>
                <cleaner>Jamal Abdillah Bin Zulkifli</cleaner>
              </day>
              
              <day name="friday">
                <date>2017/02/17</date>
                <duration unit="hour">2</duration>
                <cleaner>Jamal Abdillah Bin Zulkifli</cleaner>
              </day>
            </week>
        </month>
        
        <month name="march">
            <week>
              <day name="wednesday">
                <date>2017/03/01</date>
                <duration unit="hour">6</duration>
                <cleaner>Mustapha Aziz Bin Syakirin</cleaner>
              </day>
              
              <day name="saturday">
                <date>2017/03/04</date>
                <duration unit="hour">3</duration>
                <cleaner>Mustapha Aziz Bin Syakirin</cleaner>
              </day>
            </week>
            
            <week>
              <day name="monday">
                <date>2017/03/06</date>
                <duration unit="hour">8</duration>
                <cleaner>Mohd Yahya Bin Idris</cleaner>
              </day>
              
              <day name="thursday">
                <date>2017/03/09</date>
                <duration unit="hour">4</duration>
                <cleaner>Lisa Suhada Bin Abdul Halim</cleaner>
              </day>
            </week>
            
            <week>
              <day name="sunday">
                <date>2017/03/12</date>
                <duration unit="hour">5</duration>
                <cleaner>Muhammad Syam Bin Md Ali</cleaner>
              </day>
              
              <day name="tuesday">
                <date>2017/03/14</date>
                <duration unit="hour">6</duration>
                <cleaner>Othman Bin Kamarul Zaman</cleaner>
              </day>
              
              <day name="friday">
                <date>2017/03/17</date>
                <duration unit="hour">7</duration>
                <cleaner>Othman Bin Kamarul Zaman</cleaner>
              </day>
            </week>
        </month>
      </schedule>
    </house>
    
    <house type="terrace">
      <address>
        <street>Taman Teluk Intan</street> 
        <city>Bidor</city>
        <state>Perak</state> 
        <postcode>34780</postcode>
      </address>
      
      <owner>
        <name>Jennifer Ann Axwell</name>
        <contact>
          <phone>0154889783</phone>
          <email>jenn.ann@gmail.com</email>
        </contact>
      </owner>
      
      <date>
        <start_hire>2017/02/21</start_hire>
        <end_hire>2017/04/10</end_hire>
      </date>
      
      <schedule>
        <month name="february">
            <week>
              <day name="wednesday">
                <date>2017/02/22</date>
